### PR TITLE
Improve build system, including caching and package manager support

### PR DESCRIPTION
**Pull request by silversquirl**
This ended up having a few different changes in it:

- I fixed the example project for Linux, the library paths were wrong
- I downgraded the example project to Godot 4.2, because a) that's the version advertised in the readme and b) the run step doesn't work with that version otherwise
- I rewrote most of the `build.zig`
  - It now uses the caching system to avoid regenerating bindings every time
  - It now supports the Zig package manager :)

### CODE REVIEW

**Comment by elvisxzhou** [comment]
the red "stderr" in "run binding_generator (entrypoint.zig) stderr" hint while running bind_generator  is really annoying, any idear why?

**Comment by shiena** [comment]
@silversquirl This is a gread job.
Below is a template project for godot that uses this godot-zig from git submodule.
https://github.com/godot-zig/godot-zig-template

Could this one be modified to depend on godot-zig using build.zig.zon?
I tried but could not get it to work as I am still a zig beginner.

**Comment by silversquirl** [comment]
> the red "stderr" in "run binding_generator (entrypoint.zig) stderr" hint while running bind_generator is really annoying, any idea why?

It's because the binding generator outputs to stderr using `std.log.info`. I considered removing that but didn't want to change too much outside of the build system itself :)

I think I may have also left in a debug print somewhere. Oops!

I can make a new PR to clean those up if you like, or you can just remove the call to `std.log.info` in `binding_generator/main.zig` and the call to `std.log.debug` in `binding_generator/run_godot_dump.zig`

**Comment by silversquirl** [comment]
> Could this one be modified to depend on godot-zig using build.zig.zon? I tried but could not get it to work as I am still a zig beginner.

Sure, I can do that! I'll have a look at it in a bit :)

**Pull request merged**
